baseURL = 'https://waynemcknight.com/'
languageCode = 'en'
title = 'WM'
theme = 'congo'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'
